#!/bin/bash
echo "Returning system back into normal operational mode..."

# 1. Unblock all wireless interfaces
sudo rfkill unblock all

# 2. Turn on wireless peripherals (Wi-Fi and Bluetooth)
nmcli networking on 
sleep 1 #small pause to ensure the network manager has time to re-enable networking
bluetoothctl power on

# 3. Unblock Turbo Boost on intel CPUs (if compatible macbook pro 2011 is.)
if [ -f /sys/devices/system/cpu/intel_pstate/no_turbo ]; then
    echo 0 | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo
    fi

echo "Normal mode activated. Wi-Fi, Bluetoothand TurboBoost are back online. Enjoy your vacation!"
